title: aidon's blog
subtitle: 'a personal blog'
description: ''
keywords:
author: aidon
language: zh-CN
timezone: Asia/Shanghai

url: https://aidon-chen.github.io
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:
  lang: zh-CN

theme: butterfly

new_post_name: :title.md
default_layout: post
titlecase: false
external_link:
  enable: true
  field: site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
syntax_highlighter: highlight.js
highlight:
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  preprocess: true
  line_number: true
  tab_replace: ''

index_generator:
  path: ''
  per_page: 10
  order_by: -date

archive_generator:
  enabled: true
  per_page: 10
  yearly: true
  monthly: true
  daily: false
  order_by: -date

category_generator:
  per_page: 10

tag_generator:
  per_page: 10

deploy:
  type: ''
